spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test2
    driver-class-name: com.mysql.jdbc.Driver
  devtools:
    restart:
      enabled: true  #设置开启热部署
  activiti:
    database-schema-update: true
    history-level: full
    db-history-used: true


debug: true
